name: native_screenshot_and_share
description: Upon activation, the feature captures a screenshot and instantly prompts a share intent. Various options appear, enabling sharing via text, Bluetooth, email, or social media. This feature simplifies digital communication, seamlessly integrating screenshot capture and sharing into our digital culture. It's a practical tool for our sharing era.

version: 0.0.3
homepage: https://github.com/Arouven/native_screenshot_and_share
repository: https://github.com/Arouven/native_screenshot_and_share


environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_native_screenshot: ^1.1.2
  share_plus: ^4.5.0
  path_provider: ^2.0.5
  permission_handler: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

