name: native_screenshot_and_share
description: Upon activating the feature, it quickly takes a screenshot. Immediately following this capture, the application's share intent function is automatically engaged, prompting a comprehensive list of diverse sharing platforms to appear. Whether your intention is to send the screenshot via a text message, through Bluetooth, in an email, or even to post it on various social media channels, the options are readily accessible at your fingertips. This convenience encapsulates the spirit of modern digital communication, seamlessly blending this feature into our digitally-driven sharing culture. It's a practical tool designed to enhance efficiency in the digital sharing era.

version: 0.0.3
homepage: https://github.com/Arouven/native_screenshot_and_share
repository: https://github.com/Arouven/native_screenshot_and_share


environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_native_screenshot: ^1.1.2
  share_plus: ^4.5.0
  path_provider: ^2.0.5
  permission_handler: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

